services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=expcrl-api-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5435:5432'
